import type { CampaignMap } from "../types";

/**
 * First player campaign map — Forgotten Citadel / Citadel Path journey.
 * Nodes reference existing fc_* Tracks; presentation-only winding layout.
 */
export const FORGOTTEN_CITADEL_PATH_MAP: CampaignMap = {
  id: "forgotten_citadel_path",
  worldId: "forgotten_citadel",
  areaId: "citadel_path",
  title: "Forgotten Citadel",
  subtitle: "Find your way home through the stone lifts",
  theme: "grasslands",
  nodes: [
    {
      id: "n_fc_t01",
      worldId: "forgotten_citadel",
      scenarioId: "citadel_path",
      trackId: "fc_t01",
      x: 22,
      y: 8,
      label: "First Steps",
      type: "track",
      connections: ["n_fc_t02"],
    },
    {
      id: "n_fc_t02",
      worldId: "forgotten_citadel",
      scenarioId: "citadel_path",
      trackId: "fc_t02",
      x: 58,
      y: 14,
      label: "Rift Isles",
      type: "track",
      connections: ["n_fc_t03"],
    },
    {
      id: "n_fc_t03",
      worldId: "forgotten_citadel",
      scenarioId: "citadel_path",
      trackId: "fc_t03",
      x: 78,
      y: 24,
      label: "Portal Fork",
      type: "track",
      connections: ["n_fc_t04"],
    },
    {
      id: "n_fc_t04",
      worldId: "forgotten_citadel",
      scenarioId: "citadel_path",
      trackId: "fc_t04",
      x: 48,
      y: 32,
      label: "False Summit",
      type: "track",
      connections: ["n_fc_t05"],
    },
    {
      id: "n_fc_t05",
      worldId: "forgotten_citadel",
      scenarioId: "citadel_path",
      trackId: "fc_t05",
      x: 18,
      y: 40,
      label: "Broken Span",
      type: "track",
      connections: ["n_fc_t06"],
    },
    {
      id: "n_fc_t06",
      worldId: "forgotten_citadel",
      scenarioId: "citadel_path",
      trackId: "fc_t06",
      x: 42,
      y: 48,
      label: "Return Valve",
      type: "track",
      connections: ["n_fc_t07"],
    },
    {
      id: "n_fc_t07",
      worldId: "forgotten_citadel",
      scenarioId: "citadel_path",
      trackId: "fc_t07",
      x: 72,
      y: 54,
      label: "Helix Coil",
      type: "track",
      connections: ["n_fc_t08"],
    },
    {
      id: "n_fc_t08",
      worldId: "forgotten_citadel",
      scenarioId: "citadel_path",
      trackId: "fc_t08",
      x: 55,
      y: 64,
      label: "Gate Order",
      type: "track",
      connections: ["n_fc_t09"],
    },
    {
      id: "n_fc_t09",
      worldId: "forgotten_citadel",
      scenarioId: "citadel_path",
      trackId: "fc_t09",
      x: 28,
      y: 72,
      label: "Twin Relics",
      type: "track",
      connections: ["n_fc_t10"],
    },
    {
      id: "n_fc_t10",
      worldId: "forgotten_citadel",
      scenarioId: "citadel_path",
      trackId: "fc_t10",
      x: 52,
      y: 80,
      label: "Citadel Engine",
      type: "track",
      connections: ["n_fc_t11"],
    },
    {
      id: "n_fc_t11",
      worldId: "forgotten_citadel",
      scenarioId: "citadel_path",
      trackId: "fc_t11",
      x: 78,
      y: 86,
      label: "Track4",
      type: "track",
      connections: ["n_fc_t12"],
    },
    {
      id: "n_fc_t12",
      worldId: "forgotten_citadel",
      scenarioId: "citadel_path",
      trackId: "fc_t12",
      x: 48,
      y: 92,
      label: "Deep Vault",
      type: "track",
      connections: ["n_fc_t13"],
    },
    {
      id: "n_fc_t13",
      worldId: "forgotten_citadel",
      scenarioId: "citadel_path",
      trackId: "fc_t13",
      x: 22,
      y: 98,
      label: "Twin Currents",
      type: "track",
      connections: ["n_fc_t14"],
    },
    {
      id: "n_fc_t14",
      worldId: "forgotten_citadel",
      scenarioId: "citadel_path",
      trackId: "fc_t14",
      x: 48,
      y: 106,
      label: "Twin Currents2",
      type: "track",
      connections: ["n_fc_t15"],
    },
    {
      id: "n_fc_t15",
      worldId: "forgotten_citadel",
      scenarioId: "citadel_path",
      trackId: "fc_t15",
      x: 74,
      y: 114,
      label: "Twin Currents3",
      type: "track",
      connections: [],
    },
  ],
};
