/** Forgotten Citadel track registry */
export const FORGOTTEN_CITADEL_TRACKS = [
  { id: "t1", name: "Track 1", scenarioJson: "worlds/rainbow_realm/scenarios/prism_path/scenario.json" },
  { id: "t2", name: "Track 2", scenarioJson: "worlds/rainbow_realm/scenarios/prism_path/scenario2.json" },
  { id: "t3", name: "Track 3", scenarioJson: "worlds/rainbow_realm/scenarios/prism_path/scenario3.json" },
  { id: "t4", name: "Track 4", scenarioJson: "worlds/rainbow_realm/scenarios/prism_path/scenario4.json" },
  { id: "t5", name: "Track 5", scenarioJson: "worlds/rainbow_realm/scenarios/prism_path/scenario5.json" },
  { id: "t6", name: "Track 6", scenarioJson: "worlds/rainbow_realm/scenarios/prism_path/scenario5.json" },
  { id: "t7", name: "Track 7", scenarioJson: "worlds/rainbow_realm/scenarios/prism_path/scenario6.json" },
  { id: "t8", name: "Track 8", scenarioJson: "worlds/rainbow_realm/scenarios/prism_path/scenario7.json" },
  { id: "t9", name: "Track 9", scenarioJson: "worlds/rainbow_realm/scenarios/prism_path/scenario8.json" },
  { id: "t10", name: "Track 10", scenarioJson: "worlds/rainbow_realm/scenarios/prism_path/scenario9.json" },
  { id: "t11", name: "Track 11", scenarioJson: "worlds/rainbow_realm/scenarios/prism_path/scenario10.json" },
  { id: "t12", name: "Track 12", scenarioJson: "worlds/rainbow_realm/scenarios/prism_path/scenario11.json" },
  { id: "t13", name: "Brain Melter I", scenarioJson: "worlds/rainbow_realm/scenarios/prism_path/scenario12.json" },
  { id: "t14", name: "Brain Melter II", scenarioJson: "worlds/rainbow_realm/scenarios/prism_path/scenario13.json" },
  { id: "t15", name: "Brain Melter III", scenarioJson: "worlds/rainbow_realm/scenarios/prism_path/scenario14.json" },
  { id: "t16", name: "Brain Melter IV", scenarioJson: "worlds/rainbow_realm/scenarios/prism_path/scenario15.json" },
  { id: "t17", name: "Brain Melter V", scenarioJson: "worlds/rainbow_realm/scenarios/prism_path/scenario16.json" },
  { id: "t18", name: "Brain Melter VI", scenarioJson: "worlds/rainbow_realm/scenarios/prism_path/scenario17.json" },
  { id: "t19", name: "Brain Melter VII", scenarioJson: "worlds/rainbow_realm/scenarios/prism_path/scenario18.json" },
  { id: "t20", name: "Brain Melter VIII", scenarioJson: "worlds/rainbow_realm/scenarios/prism_path/scenario19.json" },
  { id: "t21", name: "Brain Melter IX", scenarioJson: "worlds/rainbow_realm/scenarios/prism_path/scenario20.json" },
  { id: "t22", name: "Brain Melter X", scenarioJson: "worlds/rainbow_realm/scenarios/prism_path/scenario21.json" },
  { id: "fc_t01", name: "First Steps", scenarioJson: "worlds/forgotten_citadel/scenarios/track01.json" },
  { id: "fc_t02", name: "Rift Isles", scenarioJson: "worlds/forgotten_citadel/scenarios/track02.json" },
  { id: "fc_t03", name: "Portal Fork", scenarioJson: "worlds/forgotten_citadel/scenarios/track03.json" },
  { id: "fc_t04", name: "False Summit", scenarioJson: "worlds/forgotten_citadel/scenarios/track04.json" },
  { id: "fc_t05", name: "Broken Span", scenarioJson: "worlds/forgotten_citadel/scenarios/track05.json" },
  { id: "fc_t06", name: "Return Valve", scenarioJson: "worlds/forgotten_citadel/scenarios/track06.json" },
  { id: "fc_t07", name: "Helix Coil", scenarioJson: "worlds/forgotten_citadel/scenarios/track07.json" },
  { id: "fc_t08", name: "Gate Order", scenarioJson: "worlds/forgotten_citadel/scenarios/track08.json" },
  { id: "fc_t09", name: "Twin Relics", scenarioJson: "worlds/forgotten_citadel/scenarios/track09.json" },
  { id: "fc_t10", name: "Citadel Engine", scenarioJson: "worlds/forgotten_citadel/scenarios/track10.json" },
  { id: "fc_t11", name: "Track4", scenarioJson: "worlds/forgotten_citadel/scenarios/track11.json" },
  { id: "fc_t12", name: "Deep Vault", scenarioJson: "worlds/forgotten_citadel/scenarios/track12.json" },
  { id: "fc_t13", name: "Twin Currents", scenarioJson: "worlds/forgotten_citadel/scenarios/track13.json" },
  { id: "fc_t14", name: "Twin Currents2", scenarioJson: "worlds/forgotten_citadel/scenarios/fc_t14.json" },
  { id: "fc_t15", name: "Twin Currents3", scenarioJson: "worlds/forgotten_citadel/scenarios/fc_t15.json" },
] as const;

/** Portal Fork only — for Fork visibility-variant scenarios. */
export const PORTAL_FORK_TRACK = FORGOTTEN_CITADEL_TRACKS[2];

export const FORGOTTEN_CITADEL_THEME = {
  palette: {
    L1: "#8B7355",
    L2: "#6B8E6B",
    L3: "#5C7C8A",
    L4: "#7A6B8A",
    L5: "#9A8B6E",
    L6: "#4A5568",
    L7: "#2D3748",
  },
  assets: {
    backgroundGame: "worlds/forgotten_citadel/assets/backgrounds/citadel-bg.png",
    diceFacesBase: "worlds/rainbow_realm/scenarios/prism_path/assets/dice/faces",
    diceCornerBorder: "worlds/rainbow_realm/scenarios/prism_path/assets/dice/borders/corner_flame_red.png",
    villainsBase: "worlds/rainbow_realm/scenarios/prism_path/assets/villains",
    hexTile: "worlds/forgotten_citadel/assets/tiles/hex-normal.png",
    hexTileMovable: "worlds/forgotten_citadel/assets/tiles/hex-normal-white.png",
    solidGoldGoal: true,
    backgroundMusic: "worlds/forgotten_citadel/assets/audio/citadel-bgm.mp3",
    backgroundLayers: {
      L1: "worlds/forgotten_citadel/assets/backgrounds/board-bg.png",
      L2: "worlds/forgotten_citadel/assets/backgrounds/board-bg.png",
      L3: "worlds/forgotten_citadel/assets/backgrounds/board-bg.png",
      L4: "worlds/forgotten_citadel/assets/backgrounds/board-bg.png",
      L5: "worlds/forgotten_citadel/assets/backgrounds/board-bg.png",
      L6: "worlds/forgotten_citadel/assets/backgrounds/board-bg.png",
      L7: "worlds/forgotten_citadel/assets/backgrounds/board-bg.png",
    },
  },
} as const;
