import { FORGOTTEN_CITADEL_THEME, FORGOTTEN_CITADEL_TRACKS, PORTAL_FORK_TRACK } from "./tracks";

const PORTAL_FORK_JSON = "worlds/forgotten_citadel/scenarios/track03.json";

export default {
  id: "forgotten_citadel",
  name: "Forgotten Citadel",
  desc: "Ancient stone lifts, hollow vaults, and portal machinery",
  menu: { solidColor: "#3d4f5f" },

  scenarios: [
    {
      id: "citadel_path",
      name: "Citadel Path",
      desc: "Thirteen original puzzles — vertical routing, portals, and shifting tiers",
      scenarioJson: "worlds/forgotten_citadel/scenarios/track01.json",
      theme: FORGOTTEN_CITADEL_THEME,
      tracks: [...FORGOTTEN_CITADEL_TRACKS],
    },
    {
      id: "citadel_partly_cloudynight",
      name: "Partly night",
      desc: "Mist drifts through the citadel. Your position, possible moves, and nearby stone paths remain visible.",
      visibilityMode: "night",
      scenarioJson: "worlds/forgotten_citadel/scenarios/track01.json",
      theme: FORGOTTEN_CITADEL_THEME,
      tracks: [...FORGOTTEN_CITADEL_TRACKS],
    },
    {
      id: "citadel_partly_cloudymemory",
      name: "Partly Cloudymemory",
      desc: "Mist drifts through the citadel. Your position, possible moves, and nearby stone paths remain visible.",
      visibilityMode: "memory",
      scenarioJson: "worlds/forgotten_citadel/scenarios/track01.json",
      theme: FORGOTTEN_CITADEL_THEME,
      tracks: [...FORGOTTEN_CITADEL_TRACKS],
    },
    {
      id: "citadel_partly_cloudy",
      name: "Partly Cloudy",
      desc: "Mist drifts through the citadel. Your position, possible moves, and nearby stone paths remain visible.",
      cloudMode: "cloudy",
      scenarioJson: "worlds/forgotten_citadel/scenarios/track01.json",
      theme: FORGOTTEN_CITADEL_THEME,
      tracks: [...FORGOTTEN_CITADEL_TRACKS],
    },
    {
      id: "citadel_cloudy",
      name: "Cloudy",
      desc: "Dense storm clouds conceal the citadel. Only your position, possible moves, portals, and the goal remain visible.",
      cloudMode: "full_cloud",
      scenarioJson: "worlds/forgotten_citadel/scenarios/track01.json",
      theme: FORGOTTEN_CITADEL_THEME,
      tracks: [...FORGOTTEN_CITADEL_TRACKS],
    },
    {
      id: "citadel_fork_memory",
      name: "Fork Memory",
      desc: "Ember trail — visited tiles glow; legal moves at the edge show a gold hint",
      visibilityMode: "memory",
      scenarioJson: PORTAL_FORK_JSON,
      theme: FORGOTTEN_CITADEL_THEME,
      tracks: [PORTAL_FORK_TRACK],
    },
    {
      id: "citadel_fork_lantern",
      name: "Fork Lantern",
      desc: "Candle light — bright pool around you, silhouettes at the edge, void beyond",
      visibilityMode: "lantern",
      scenarioJson: PORTAL_FORK_JSON,
      theme: FORGOTTEN_CITADEL_THEME,
      tracks: [PORTAL_FORK_TRACK],
    },
    {
      id: "citadel_fork_echo",
      name: "Fork Echo",
      desc: "Ghost footprints — your recent steps linger as faint echoes",
      visibilityMode: "echo",
      scenarioJson: PORTAL_FORK_JSON,
      theme: FORGOTTEN_CITADEL_THEME,
      tracks: [PORTAL_FORK_TRACK],
    },
    {
      id: "citadel_fork_night",
      name: "Fork Night",
      desc: "Every hex faded; only your current tile stays lit",
      visibilityMode: "night",
      scenarioJson: PORTAL_FORK_JSON,
      theme: FORGOTTEN_CITADEL_THEME,
      tracks: [PORTAL_FORK_TRACK],
    },
    {
      id: "citadel_fork_invisible",
      name: "Fork Invisible",
      desc: "Only your current tile is visible",
      visibilityMode: "invisible",
      scenarioJson: PORTAL_FORK_JSON,
      theme: FORGOTTEN_CITADEL_THEME,
      tracks: [PORTAL_FORK_TRACK],
    },
    {
      id: "citadel_fork_crystal_vision",
      name: "Fork Crystal Vision",
      desc: "Starfield void — goal and portals shine; terrain on sight-lines to beacons",
      visibilityMode: "crystal_vision",
      scenarioJson: PORTAL_FORK_JSON,
      theme: FORGOTTEN_CITADEL_THEME,
      tracks: [PORTAL_FORK_TRACK],
    },
  ],
} as const;
