import { FORGOTTEN_CITADEL_THEME, FORGOTTEN_CITADEL_TRACKS, PORTAL_FORK_TRACK } from "./tracks";

const PORTAL_FORK_JSON = "worlds/forgotten_citadel/scenarios/track03.json";

export default {
  id: "forgotten_citadel",
  name: "Forgotten Citadel",
  desc: "Ancient stone lifts, hollow vaults, and portal machinery",
  menu: { solidColor: "#3d4f5f" },

  scenarios: [
    {
      id: "citadel_path",
      name: "Citadel Path",
      desc: "Thirteen original puzzles — vertical routing, portals, and shifting tiers",
      scenarioJson: "worlds/forgotten_citadel/scenarios/track01.json",
      theme: FORGOTTEN_CITADEL_THEME,
      tracks: [...FORGOTTEN_CITADEL_TRACKS],
    },
    {
      id: "citadel_partly_cloudy",
      name: "Partly Cloudy",
      desc: "Mist drifts through the citadel. Your position, possible moves, and nearby stone paths remain visible.",
      cloudMode: "cloudy",
      scenarioJson: "worlds/forgotten_citadel/scenarios/track01.json",
      theme: FORGOTTEN_CITADEL_THEME,
      tracks: [...FORGOTTEN_CITADEL_TRACKS],
    },
    {
      id: "citadel_cloudy",
      name: "Cloudy",
      desc: "Dense storm clouds conceal the citadel. Only your position, possible moves, portals, and the goal remain visible.",
      cloudMode: "full_cloud",
      scenarioJson: "worlds/forgotten_citadel/scenarios/track01.json",
      theme: FORGOTTEN_CITADEL_THEME,
      tracks: [...FORGOTTEN_CITADEL_TRACKS],
    },
    {
      id: "citadel_fork_memory",
      name: "Fork Memory",
      desc: "Visited tiles stay visible",
      visibilityMode: "memory",
      scenarioJson: PORTAL_FORK_JSON,
      theme: FORGOTTEN_CITADEL_THEME,
      tracks: [PORTAL_FORK_TRACK],
    },
    {
      id: "citadel_fork_lantern",
      name: "Fork Lantern",
      desc: "Soft light radius around you",
      visibilityMode: "lantern",
      scenarioJson: PORTAL_FORK_JSON,
      theme: FORGOTTEN_CITADEL_THEME,
      tracks: [PORTAL_FORK_TRACK],
    },
    {
      id: "citadel_fork_echo",
      name: "Fork Echo",
      desc: "Ghost traces where you recently stepped",
      visibilityMode: "echo",
      scenarioJson: PORTAL_FORK_JSON,
      theme: FORGOTTEN_CITADEL_THEME,
      tracks: [PORTAL_FORK_TRACK],
    },
    {
      id: "citadel_fork_night",
      name: "Fork Night",
      desc: "Dark sky; only your tile + legal moves show",
      visibilityMode: "night",
      scenarioJson: PORTAL_FORK_JSON,
      theme: FORGOTTEN_CITADEL_THEME,
      tracks: [PORTAL_FORK_TRACK],
    },
    {
      id: "citadel_fork_invisible",
      name: "Fork Invisible",
      desc: "Only your current tile is visible",
      visibilityMode: "invisible",
      scenarioJson: PORTAL_FORK_JSON,
      theme: FORGOTTEN_CITADEL_THEME,
      tracks: [PORTAL_FORK_TRACK],
    },
    {
      id: "citadel_fork_crystal_vision",
      name: "Fork Crystal Vision",
      desc: "Misty board, but goal & portals stay visible",
      visibilityMode: "crystal_vision",
      scenarioJson: PORTAL_FORK_JSON,
      theme: FORGOTTEN_CITADEL_THEME,
      tracks: [PORTAL_FORK_TRACK],
    },
  ],
} as const;
